const vocabularyData = [
  {
    "id": "1",
    "category": "Cuộc sống",
    "vi": "phanh (xe)",
    "jp": "ブレーキ",
    "kana": "ぶれーき",
    "en": "brake",
    "ipa": "/breɪk/",
    "cn": "刹车",
    "pinyin": "shāchē",
    "ko": "브레이크",
    "koreanReading": "beureikeu",
    "note": "",
    "examples": {
      "vi": "Hãy đạp phanh.",
      "jp": "ブレーキをかけてください。",
      "en": "Please apply the brake.",
      "cn": "请踩刹车。",
      "ko": "브레이크를 밟아 주세요."
    }
  },
  {
    "id": "2",
    "category": "Du lịch",
    "vi": "sân bay",
    "jp": "空港",
    "kana": "くうこう",
    "en": "airport",
    "ipa": "/ˈeəpɔːrt/",
    "cn": "机场",
    "pinyin": "jīchǎng",
    "ko": "공항",
    "koreanReading": "gonghang",
    "note": "",
    "examples": {
      "vi": "Tôi đi đến sân bay.",
      "jp": "空港へ行きます。",
      "en": "I go to the airport.",
      "cn": "我去机场。",
      "ko": "공항에 갑니다."
    }
  },
  {
    "id": "3",
    "category": "Cuộc sống",
    "vi": "gia đình",
    "jp": "家族",
    "kana": "かぞく",
    "en": "family",
    "ipa": "/ˈfæməli/",
    "cn": "家人",
    "pinyin": "jiārén",
    "ko": "가족",
    "koreanReading": "gajok",
    "note": "",
    "examples": {
      "vi": "Đây là gia đình tôi.",
      "jp": "これは私の家族です。",
      "en": "This is my family.",
      "cn": "这是我的家人。",
      "ko": "이것은 제 가족입니다."
    }
  },
  {
    "id": "4",
    "category": "Du lịch",
    "vi": "khách sạn",
    "jp": "ホテル",
    "kana": "ほてる",
    "en": "hotel",
    "ipa": "/hoʊˈtel/",
    "cn": "酒店",
    "pinyin": "jiǔdiàn",
    "ko": "호텔",
    "koreanReading": "hotel",
    "note": "",
    "examples": {
      "vi": "Tôi đã đặt khách sạn.",
      "jp": "ホテルを予約しました。",
      "en": "I booked a hotel.",
      "cn": "我预订了酒店。",
      "ko": "호텔을 예약했습니다."
    }
  },
  {
    "id": "5",
    "category": "Công việc",
    "vi": "cuộc họp",
    "jp": "会議",
    "kana": "かいぎ",
    "en": "meeting",
    "ipa": "/ˈmiːtɪŋ/",
    "cn": "会议",
    "pinyin": "huìyì",
    "ko": "회의",
    "koreanReading": "hoeui",
    "note": "",
    "examples": {
      "vi": "Tôi có cuộc họp lúc 9 giờ.",
      "jp": "9時に会議があります。",
      "en": "I have a meeting at nine.",
      "cn": "我九点有会议。",
      "ko": "저는 9시에 회의가 있습니다."
    }
  },
  {
    "id": "6",
    "category": "Gia đình",
    "vi": "gia đình",
    "jp": "家族",
    "kana": "かぞく",
    "en": "family",
    "ipa": "/ˈfæməli/",
    "cn": "家人",
    "pinyin": "jiārén",
    "ko": "가족",
    "koreanReading": "gajok",
    "note": "",
    "examples": {
      "vi": "Đây là gia đình tôi.",
      "jp": "これは私の家族です。",
      "en": "This is my family.",
      "cn": "这是我的家人。",
      "ko": "이것은 제 가족입니다。"
    }
  },
  {
    "id": "7",
    "category": "Gia đình",
    "vi": "bố",
    "jp": "父",
    "kana": "ちち",
    "en": "father",
    "ipa": "/ˈfɑːðər/",
    "cn": "爸爸",
    "pinyin": "bàba",
    "ko": "아버지",
    "koreanReading": "abeoji",
    "note": "",
    "examples": {
      "vi": "Bố tôi rất vui tính.",
      "jp": "父はとても明るいです。",
      "en": "My father is very cheerful.",
      "cn": "我爸爸很开朗。",
      "ko": "아버지는 아주 밝으십니다。"
    }
  },
  {
    "id": "8",
    "category": "Gia đình",
    "vi": "mẹ",
    "jp": "母",
    "kana": "はは",
    "en": "mother",
    "ipa": "/ˈmʌðər/",
    "cn": "妈妈",
    "pinyin": "māma",
    "ko": "어머니",
    "koreanReading": "eomeoni",
    "note": "",
    "examples": {
      "vi": "Mẹ tôi nấu ăn rất ngon.",
      "jp": "母は料理がとても上手です。",
      "en": "My mother cooks very well.",
      "cn": "我妈妈做饭很好吃。",
      "ko": "어머니는 요리를 아주 잘하십니다。"
    }
  },
  {
    "id": "9",
    "category": "Gia đình",
    "vi": "anh trai",
    "jp": "兄",
    "kana": "あに",
    "en": "older brother",
    "ipa": "/ˌoʊldər ˈbrʌðər/",
    "cn": "哥哥",
    "pinyin": "gēge",
    "ko": "형",
    "koreanReading": "hyeong",
    "note": "",
    "examples": {
      "vi": "Anh trai tôi thích thể thao.",
      "jp": "兄はスポーツが好きです。",
      "en": "My older brother likes sports.",
      "cn": "我哥哥喜欢运动。",
      "ko": "형은 운동을 좋아합니다。"
    }
  },
  {
    "id": "10",
    "category": "Gia đình",
    "vi": "chị gái",
    "jp": "姉",
    "kana": "あね",
    "en": "older sister",
    "ipa": "/ˌoʊldər ˈsɪstər/",
    "cn": "姐姐",
    "pinyin": "jiějie",
    "ko": "누나",
    "koreanReading": "nuna",
    "note": "",
    "examples": {
      "vi": "Chị gái tôi hay cười.",
      "jp": "姉はよく笑います。",
      "en": "My older sister smiles a lot.",
      "cn": "我姐姐常常笑。",
      "ko": "누나는 자주 웃습니다。"
    }
  },
  {
    "id": "11",
    "category": "Gia đình",
    "vi": "em trai",
    "jp": "弟",
    "kana": "おとうと",
    "en": "younger brother",
    "ipa": "/ˌjʌŋɡər ˈbrʌðər/",
    "cn": "弟弟",
    "pinyin": "dìdi",
    "ko": "남동생",
    "koreanReading": "namdongsaeng",
    "note": "",
    "examples": {
      "vi": "Em trai tôi rất khỏe.",
      "jp": "弟はとても元気です。",
      "en": "My younger brother is very energetic.",
      "cn": "我弟弟很有精神。",
      "ko": "남동생은 아주 활기찹니다。"
    }
  },
  {
    "id": "12",
    "category": "Gia đình",
    "vi": "em gái",
    "jp": "妹",
    "kana": "いもうと",
    "en": "younger sister",
    "ipa": "/ˌjʌŋɡər ˈsɪstər/",
    "cn": "妹妹",
    "pinyin": "mèimei",
    "ko": "여동생",
    "koreanReading": "yeodongsaeng",
    "note": "",
    "examples": {
      "vi": "Em gái tôi thích hát.",
      "jp": "妹は歌うことが好きです。",
      "en": "My younger sister likes singing.",
      "cn": "我妹妹喜欢唱歌。",
      "ko": "여동생은 노래하는 것을 좋아합니다。"
    }
  },
  {
    "id": "13",
    "category": "Gia đình",
    "vi": "ông",
    "jp": "祖父",
    "kana": "そふ",
    "en": "grandfather",
    "ipa": "/ˈɡrændˌfɑːðər/",
    "cn": "爷爷",
    "pinyin": "yéye",
    "ko": "할아버지",
    "koreanReading": "harabeoji",
    "note": "",
    "examples": {
      "vi": "Ông tôi kể chuyện rất hay.",
      "jp": "祖父は話がとても上手です。",
      "en": "My grandfather tells great stories.",
      "cn": "我爷爷讲故事很好。",
      "ko": "할아버지는 이야기를 아주 잘하십니다。"
    }
  },
  {
    "id": "14",
    "category": "Gia đình",
    "vi": "bà",
    "jp": "祖母",
    "kana": "そぼ",
    "en": "grandmother",
    "ipa": "/ˈɡrændˌmʌðər/",
    "cn": "奶奶",
    "pinyin": "nǎinai",
    "ko": "할머니",
    "koreanReading": "halmeoni",
    "note": "",
    "examples": {
      "vi": "Bà tôi rất hiền.",
      "jp": "祖母はとても優しいです。",
      "en": "My grandmother is very kind.",
      "cn": "我奶奶很温柔。",
      "ko": "할머니는 아주 다정하십니다。"
    }
  },
  {
    "id": "15",
    "category": "Gia đình",
    "vi": "con",
    "jp": "子ども",
    "kana": "こども",
    "en": "child",
    "ipa": "/tʃaɪld/",
    "cn": "孩子",
    "pinyin": "háizi",
    "ko": "아이",
    "koreanReading": "ai",
    "note": "",
    "examples": {
      "vi": "Con tôi cười rất đáng yêu.",
      "jp": "子どもはとてもかわいく笑います。",
      "en": "My child smiles very cutely.",
      "cn": "我的孩子笑得很可爱。",
      "ko": "아이는 아주 귀엽게 웃습니다。"
    }
  },
  {
    "id": "16",
    "category": "Du lịch",
    "vi": "ga tàu",
    "jp": "駅",
    "kana": "えき",
    "en": "station",
    "ipa": "/ˈsteɪʃən/",
    "cn": "车站",
    "pinyin": "chēzhàn",
    "ko": "역",
    "koreanReading": "yeok",
    "note": "",
    "examples": {
      "vi": "Tôi đang ở ga tàu.",
      "jp": "私は駅にいます。",
      "en": "I am at the station.",
      "cn": "我在车站。",
      "ko": "저는 역에 있습니다."
    }
  },
  {
    "id": "17",
    "category": "Du lịch",
    "vi": "vé",
    "jp": "切符",
    "kana": "きっぷ",
    "en": "ticket",
    "ipa": "/ˈtɪkɪt/",
    "cn": "票",
    "pinyin": "piào",
    "ko": "표",
    "koreanReading": "pyo",
    "note": "",
    "examples": {
      "vi": "Tôi đã mua vé.",
      "jp": "切符を買いました。",
      "en": "I bought a ticket.",
      "cn": "我买了票。",
      "ko": "표를 샀습니다."
    }
  },
  {
    "id": "18",
    "category": "Du lịch",
    "vi": "tàu điện",
    "jp": "電車",
    "kana": "でんしゃ",
    "en": "train",
    "ipa": "/treɪn/",
    "cn": "火车",
    "pinyin": "huǒchē",
    "ko": "기차",
    "koreanReading": "gicha",
    "note": "",
    "examples": {
      "vi": "Tôi đi tàu điện.",
      "jp": "電車で行きます。",
      "en": "I go by train.",
      "cn": "我坐火车去。",
      "ko": "기차로 갑니다."
    }
  },
  {
    "id": "19",
    "category": "Du lịch",
    "vi": "xe buýt",
    "jp": "バス",
    "kana": "ばす",
    "en": "bus",
    "ipa": "/bʌs/",
    "cn": "公交车",
    "pinyin": "gōngjiāochē",
    "ko": "버스",
    "koreanReading": "beoseu",
    "note": "",
    "examples": {
      "vi": "Tôi đi xe buýt.",
      "jp": "バスで行きます。",
      "en": "I go by bus.",
      "cn": "我坐公交车去。",
      "ko": "버스로 갑니다."
    }
  },
  {
    "id": "20",
    "category": "Du lịch",
    "vi": "bản đồ",
    "jp": "地図",
    "kana": "ちず",
    "en": "map",
    "ipa": "/mæp/",
    "cn": "地图",
    "pinyin": "dìtú",
    "ko": "지도",
    "koreanReading": "jido",
    "note": "",
    "examples": {
      "vi": "Bản đồ rất hữu ích.",
      "jp": "地図は便利です。",
      "en": "The map is useful.",
      "cn": "地图很有用。",
      "ko": "지도는 유용합니다."
    }
  },
  {
    "id": "21",
    "category": "Du lịch",
    "vi": "hành lý",
    "jp": "荷物",
    "kana": "にもつ",
    "en": "luggage",
    "ipa": "/ˈlʌɡɪdʒ/",
    "cn": "行李",
    "pinyin": "xíngli",
    "ko": "짐",
    "koreanReading": "jim",
    "note": "",
    "examples": {
      "vi": "Hành lý của tôi ở đây.",
      "jp": "荷物はここです。",
      "en": "My luggage is here.",
      "cn": "我的行李在这里。",
      "ko": "제 짐은 여기 있습니다."
    }
  },
  {
    "id": "22",
    "category": "Du lịch",
    "vi": "hộ chiếu",
    "jp": "パスポート",
    "kana": "ぱすぽーと",
    "en": "passport",
    "ipa": "/ˈpæspɔːrt/",
    "cn": "护照",
    "pinyin": "hùzhào",
    "ko": "여권",
    "koreanReading": "yeogwon",
    "note": "",
    "examples": {
      "vi": "Tôi mang theo hộ chiếu.",
      "jp": "パスポートを持っています。",
      "en": "I have my passport.",
      "cn": "我带着护照。",
      "ko": "여권을 가지고 있습니다."
    }
  },
  {
    "id": "23",
    "category": "Du lịch",
    "vi": "ảnh",
    "jp": "写真",
    "kana": "しゃしん",
    "en": "photo",
    "ipa": "/ˈfoʊtoʊ/",
    "cn": "照片",
    "pinyin": "zhàopiàn",
    "ko": "사진",
    "koreanReading": "sajin",
    "note": "",
    "examples": {
      "vi": "Tôi chụp một bức ảnh.",
      "jp": "写真を撮ります。",
      "en": "I take a photo.",
      "cn": "我拍照片。",
      "ko": "사진을 찍습니다."
    }
  },
  {
    "id": "24",
    "category": "Du lịch",
    "vi": "công viên",
    "jp": "公園",
    "kana": "こうえん",
    "en": "park",
    "ipa": "/pɑːrk/",
    "cn": "公园",
    "pinyin": "gōngyuán",
    "ko": "공원",
    "koreanReading": "gongwon",
    "note": "",
    "examples": {
      "vi": "Chúng tôi đi công viên.",
      "jp": "公園へ行きます。",
      "en": "We go to the park.",
      "cn": "我们去公园。",
      "ko": "우리는 공원에 갑니다."
    }
  },
  {
    "id": "25",
    "category": "Du lịch",
    "vi": "du lịch",
    "jp": "旅行",
    "kana": "りょこう",
    "en": "travel",
    "ipa": "/ˈtrævəl/",
    "cn": "旅行",
    "pinyin": "lǚxíng",
    "ko": "여행",
    "koreanReading": "yeohaeng",
    "note": "",
    "examples": {
      "vi": "Tôi thích đi du lịch.",
      "jp": "旅行が好きです。",
      "en": "I like to travel.",
      "cn": "我喜欢旅行。",
      "ko": "저는 여행을 좋아합니다."
    }
  },
  {
    "id": "26",
    "category": "Mua sắm",
    "vi": "cửa hàng",
    "jp": "店",
    "kana": "みせ",
    "en": "store",
    "ipa": "/stɔːr/",
    "cn": "商店",
    "pinyin": "shāngdiàn",
    "ko": "가게",
    "koreanReading": "gage",
    "note": "",
    "examples": {
      "vi": "Tôi vào cửa hàng.",
      "jp": "店に入ります。",
      "en": "I go into the store.",
      "cn": "我走进商店。",
      "ko": "가게에 들어갑니다."
    }
  },
  {
    "id": "27",
    "category": "Mua sắm",
    "vi": "tiền",
    "jp": "お金",
    "kana": "おかね",
    "en": "money",
    "ipa": "/ˈmʌni/",
    "cn": "钱",
    "pinyin": "qián",
    "ko": "돈",
    "koreanReading": "don",
    "note": "",
    "examples": {
      "vi": "Tôi có đủ tiền.",
      "jp": "お金があります。",
      "en": "I have enough money.",
      "cn": "我有足够的钱。",
      "ko": "돈이 충분합니다."
    }
  },
  {
    "id": "28",
    "category": "Mua sắm",
    "vi": "giá cả",
    "jp": "値段",
    "kana": "ねだん",
    "en": "price",
    "ipa": "/praɪs/",
    "cn": "价格",
    "pinyin": "jiàgé",
    "ko": "가격",
    "koreanReading": "gagyeok",
    "note": "",
    "examples": {
      "vi": "Giá này rất tốt.",
      "jp": "この値段は安いです。",
      "en": "This price is good.",
      "cn": "这个价格很好。",
      "ko": "이 가격은 좋습니다."
    }
  },
  {
    "id": "29",
    "category": "Mua sắm",
    "vi": "giảm giá",
    "jp": "割引",
    "kana": "わりびき",
    "en": "discount",
    "ipa": "/ˈdɪskaʊnt/",
    "cn": "折扣",
    "pinyin": "zhékòu",
    "ko": "할인",
    "koreanReading": "harin",
    "note": "",
    "examples": {
      "vi": "Hôm nay có giảm giá.",
      "jp": "今日は割引があります。",
      "en": "There is a discount today.",
      "cn": "今天有折扣。",
      "ko": "오늘은 할인이 있습니다."
    }
  },
  {
    "id": "30",
    "category": "Mua sắm",
    "vi": "hóa đơn",
    "jp": "レシート",
    "kana": "れしーと",
    "en": "receipt",
    "ipa": "/rɪˈsiːt/",
    "cn": "收据",
    "pinyin": "shōujù",
    "ko": "영수증",
    "koreanReading": "yeongsujeung",
    "note": "",
    "examples": {
      "vi": "Tôi giữ hóa đơn.",
      "jp": "レシートを持っています。",
      "en": "I keep the receipt.",
      "cn": "我留着收据。",
      "ko": "영수증을 가지고 있습니다."
    }
  },
  {
    "id": "31",
    "category": "Mua sắm",
    "vi": "thẻ",
    "jp": "カード",
    "kana": "かーど",
    "en": "card",
    "ipa": "/kɑːrd/",
    "cn": "卡",
    "pinyin": "kǎ",
    "ko": "카드",
    "koreanReading": "kadeu",
    "note": "",
    "examples": {
      "vi": "Tôi trả bằng thẻ.",
      "jp": "カードで払います。",
      "en": "I pay by card.",
      "cn": "我用卡付款。",
      "ko": "카드로 계산합니다."
    }
  },
  {
    "id": "32",
    "category": "Mua sắm",
    "vi": "tiền mặt",
    "jp": "現金",
    "kana": "げんきん",
    "en": "cash",
    "ipa": "/kæʃ/",
    "cn": "现金",
    "pinyin": "xiànjīn",
    "ko": "현금",
    "koreanReading": "hyeongeum",
    "note": "",
    "examples": {
      "vi": "Tôi có tiền mặt.",
      "jp": "現金があります。",
      "en": "I have cash.",
      "cn": "我有现金。",
      "ko": "현금이 있습니다."
    }
  },
  {
    "id": "33",
    "category": "Mua sắm",
    "vi": "túi",
    "jp": "袋",
    "kana": "ふくろ",
    "en": "bag",
    "ipa": "/bæɡ/",
    "cn": "袋子",
    "pinyin": "dàizi",
    "ko": "봉투",
    "koreanReading": "bongtu",
    "note": "",
    "examples": {
      "vi": "Tôi cần một cái túi.",
      "jp": "袋をください。",
      "en": "I need a bag.",
      "cn": "请给我一个袋子。",
      "ko": "봉투 하나 주세요."
    }
  },
  {
    "id": "34",
    "category": "Mua sắm",
    "vi": "quần áo",
    "jp": "服",
    "kana": "ふく",
    "en": "clothes",
    "ipa": "/kloʊðz/",
    "cn": "衣服",
    "pinyin": "yīfu",
    "ko": "옷",
    "koreanReading": "ot",
    "note": "",
    "examples": {
      "vi": "Tôi thích quần áo này.",
      "jp": "この服が好きです。",
      "en": "I like these clothes.",
      "cn": "我喜欢这件衣服。",
      "ko": "이 옷이 마음에 듭니다."
    }
  },
  {
    "id": "35",
    "category": "Mua sắm",
    "vi": "giày",
    "jp": "靴",
    "kana": "くつ",
    "en": "shoes",
    "ipa": "/ʃuːz/",
    "cn": "鞋",
    "pinyin": "xié",
    "ko": "신발",
    "koreanReading": "sinbal",
    "note": "",
    "examples": {
      "vi": "Tôi muốn mua giày.",
      "jp": "靴を買いたいです。",
      "en": "I want to buy shoes.",
      "cn": "我想买鞋。",
      "ko": "신발을 사고 싶습니다."
    }
  },
  {
    "id": "36",
    "category": "Thời tiết",
    "vi": "trời",
    "jp": "空",
    "kana": "そら",
    "en": "sky",
    "ipa": "/skaɪ/",
    "cn": "天空",
    "pinyin": "tiānkōng",
    "ko": "하늘",
    "koreanReading": "haneul",
    "note": "",
    "examples": {
      "vi": "Bầu trời rất đẹp.",
      "jp": "空がきれいです。",
      "en": "The sky is beautiful.",
      "cn": "天空很美。",
      "ko": "하늘이 아름답습니다."
    }
  },
  {
    "id": "37",
    "category": "Thời tiết",
    "vi": "mặt trời",
    "jp": "太陽",
    "kana": "たいよう",
    "en": "sun",
    "ipa": "/sʌn/",
    "cn": "太阳",
    "pinyin": "tàiyáng",
    "ko": "태양",
    "koreanReading": "taeyang",
    "note": "",
    "examples": {
      "vi": "Mặt trời đang chiếu sáng.",
      "jp": "太陽が出ています。",
      "en": "The sun is shining.",
      "cn": "太阳出来了。",
      "ko": "태양이 빛나고 있습니다."
    }
  },
  {
    "id": "38",
    "category": "Thời tiết",
    "vi": "mưa",
    "jp": "雨",
    "kana": "あめ",
    "en": "rain",
    "ipa": "/reɪn/",
    "cn": "雨",
    "pinyin": "yǔ",
    "ko": "비",
    "koreanReading": "bi",
    "note": "",
    "examples": {
      "vi": "Hôm nay có mưa.",
      "jp": "今日は雨です。",
      "en": "It is raining today.",
      "cn": "今天下雨。",
      "ko": "오늘은 비가 옵니다."
    }
  },
  {
    "id": "39",
    "category": "Thời tiết",
    "vi": "tuyết",
    "jp": "雪",
    "kana": "ゆき",
    "en": "snow",
    "ipa": "/snoʊ/",
    "cn": "雪",
    "pinyin": "xuě",
    "ko": "눈",
    "koreanReading": "nun",
    "note": "",
    "examples": {
      "vi": "Mùa đông có tuyết.",
      "jp": "冬は雪が降ります。",
      "en": "It snows in winter.",
      "cn": "冬天下雪。",
      "ko": "겨울에는 눈이 옵니다."
    }
  },
  {
    "id": "40",
    "category": "Thời tiết",
    "vi": "gió",
    "jp": "風",
    "kana": "かぜ",
    "en": "wind",
    "ipa": "/wɪnd/",
    "cn": "风",
    "pinyin": "fēng",
    "ko": "바람",
    "koreanReading": "baram",
    "note": "",
    "examples": {
      "vi": "Gió hôm nay rất mát.",
      "jp": "今日は風が気持ちいいです。",
      "en": "The wind feels nice today.",
      "cn": "今天风很舒服。",
      "ko": "오늘 바람이 시원합니다."
    }
  },
  {
    "id": "41",
    "category": "Thời tiết",
    "vi": "mây",
    "jp": "雲",
    "kana": "くも",
    "en": "cloud",
    "ipa": "/klaʊd/",
    "cn": "云",
    "pinyin": "yún",
    "ko": "구름",
    "koreanReading": "gureum",
    "note": "",
    "examples": {
      "vi": "Có nhiều mây trên trời.",
      "jp": "空に雲があります。",
      "en": "There are clouds in the sky.",
      "cn": "天上有云。",
      "ko": "하늘에 구름이 있습니다."
    }
  },
  {
    "id": "42",
    "category": "Thời tiết",
    "vi": "nóng",
    "jp": "暑い",
    "kana": "あつい",
    "en": "hot",
    "ipa": "/hɑːt/",
    "cn": "热",
    "pinyin": "rè",
    "ko": "덥다",
    "koreanReading": "deopda",
    "note": "",
    "examples": {
      "vi": "Hôm nay rất nóng.",
      "jp": "今日は暑いです。",
      "en": "It is hot today.",
      "cn": "今天很热。",
      "ko": "오늘은 덥습니다."
    }
  },
  {
    "id": "43",
    "category": "Thời tiết",
    "vi": "lạnh",
    "jp": "寒い",
    "kana": "さむい",
    "en": "cold",
    "ipa": "/koʊld/",
    "cn": "冷",
    "pinyin": "lěng",
    "ko": "춥다",
    "koreanReading": "chupda",
    "note": "",
    "examples": {
      "vi": "Hôm nay khá lạnh.",
      "jp": "今日は寒いです。",
      "en": "It is cold today.",
      "cn": "今天很冷。",
      "ko": "오늘은 춥습니다."
    }
  },
  {
    "id": "44",
    "category": "Thời tiết",
    "vi": "ấm áp",
    "jp": "暖かい",
    "kana": "あたたかい",
    "en": "warm",
    "ipa": "/wɔːrm/",
    "cn": "暖和",
    "pinyin": "nuǎnhuo",
    "ko": "따뜻하다",
    "koreanReading": "ttatteuthada",
    "note": "",
    "examples": {
      "vi": "Mùa xuân rất ấm áp.",
      "jp": "春は暖かいです。",
      "en": "Spring is warm.",
      "cn": "春天很暖和。",
      "ko": "봄은 따뜻합니다."
    }
  },
  {
    "id": "45",
    "category": "Thời tiết",
    "vi": "trong xanh",
    "jp": "晴れ",
    "kana": "はれ",
    "en": "sunny",
    "ipa": "/ˈsʌni/",
    "cn": "晴天",
    "pinyin": "qíngtiān",
    "ko": "맑다",
    "koreanReading": "malgda",
    "note": "",
    "examples": {
      "vi": "Hôm nay trời trong xanh.",
      "jp": "今日は晴れです。",
      "en": "It is sunny today.",
      "cn": "今天是晴天。",
      "ko": "오늘은 날씨가 맑습니다."
    }
  },
  {
    "id": "46",
    "category": "Động vật",
    "vi": "chó",
    "jp": "犬",
    "kana": "いぬ",
    "en": "dog",
    "ipa": "/dɔːɡ/",
    "cn": "狗",
    "pinyin": "gǒu",
    "ko": "개",
    "koreanReading": "gae",
    "note": "",
    "examples": {
      "vi": "Con chó rất đáng yêu.",
      "jp": "犬はとてもかわいいです。",
      "en": "The dog is very cute.",
      "cn": "这只狗很可爱。",
      "ko": "강아지가 아주 귀엽습니다."
    }
  },
  {
    "id": "47",
    "category": "Động vật",
    "vi": "mèo",
    "jp": "猫",
    "kana": "ねこ",
    "en": "cat",
    "ipa": "/kæt/",
    "cn": "猫",
    "pinyin": "māo",
    "ko": "고양이",
    "koreanReading": "goyangi",
    "note": "",
    "examples": {
      "vi": "Con mèo đang ngủ.",
      "jp": "猫は寝ています。",
      "en": "The cat is sleeping.",
      "cn": "猫在睡觉。",
      "ko": "고양이가 자고 있습니다."
    }
  },
  {
    "id": "48",
    "category": "Động vật",
    "vi": "chim",
    "jp": "鳥",
    "kana": "とり",
    "en": "bird",
    "ipa": "/bɜːrd/",
    "cn": "鸟",
    "pinyin": "niǎo",
    "ko": "새",
    "koreanReading": "sae",
    "note": "",
    "examples": {
      "vi": "Con chim đang hót.",
      "jp": "鳥が鳴いています。",
      "en": "The bird is singing.",
      "cn": "鸟在唱歌。",
      "ko": "새가 노래하고 있습니다."
    }
  },
  {
    "id": "49",
    "category": "Động vật",
    "vi": "cá",
    "jp": "魚",
    "kana": "さかな",
    "en": "fish",
    "ipa": "/fɪʃ/",
    "cn": "鱼",
    "pinyin": "yú",
    "ko": "물고기",
    "koreanReading": "mulgogi",
    "note": "",
    "examples": {
      "vi": "Con cá đang bơi.",
      "jp": "魚が泳いでいます。",
      "en": "The fish is swimming.",
      "cn": "鱼在游泳。",
      "ko": "물고기가 헤엄치고 있습니다."
    }
  },
  {
    "id": "50",
    "category": "Động vật",
    "vi": "thỏ",
    "jp": "兎",
    "kana": "うさぎ",
    "en": "rabbit",
    "ipa": "/ˈræbɪt/",
    "cn": "兔子",
    "pinyin": "tùzi",
    "ko": "토끼",
    "koreanReading": "tokki",
    "note": "",
    "examples": {
      "vi": "Con thỏ chạy rất nhanh.",
      "jp": "兎は速く走ります。",
      "en": "The rabbit runs fast.",
      "cn": "兔子跑得很快。",
      "ko": "토끼가 빨리 달립니다."
    }
  },
  {
    "id": "51",
    "category": "Động vật",
    "vi": "ngựa",
    "jp": "馬",
    "kana": "うま",
    "en": "horse",
    "ipa": "/hɔːrs/",
    "cn": "马",
    "pinyin": "mǎ",
    "ko": "말",
    "koreanReading": "mal",
    "note": "",
    "examples": {
      "vi": "Con ngựa rất khỏe.",
      "jp": "馬はとても元気です。",
      "en": "The horse is very strong.",
      "cn": "马很强壮。",
      "ko": "말은 아주 튼튼합니다."
    }
  },
  {
    "id": "52",
    "category": "Động vật",
    "vi": "bò",
    "jp": "牛",
    "kana": "うし",
    "en": "cow",
    "ipa": "/kaʊ/",
    "cn": "牛",
    "pinyin": "niú",
    "ko": "소",
    "koreanReading": "so",
    "note": "",
    "examples": {
      "vi": "Con bò đang ăn cỏ.",
      "jp": "牛は草を食べています。",
      "en": "The cow is eating grass.",
      "cn": "牛在吃草。",
      "ko": "소가 풀을 먹고 있습니다."
    }
  },
  {
    "id": "53",
    "category": "Động vật",
    "vi": "hổ",
    "jp": "虎",
    "kana": "とら",
    "en": "tiger",
    "ipa": "/ˈtaɪɡər/",
    "cn": "老虎",
    "pinyin": "lǎohǔ",
    "ko": "호랑이",
    "koreanReading": "horangi",
    "note": "",
    "examples": {
      "vi": "Con hổ rất mạnh.",
      "jp": "虎はとても強いです。",
      "en": "The tiger is very strong.",
      "cn": "老虎很强壮。",
      "ko": "호랑이는 아주 강합니다."
    }
  },
  {
    "id": "54",
    "category": "Động vật",
    "vi": "voi",
    "jp": "象",
    "kana": "ぞう",
    "en": "elephant",
    "ipa": "/ˈelɪfənt/",
    "cn": "大象",
    "pinyin": "dàxiàng",
    "ko": "코끼리",
    "koreanReading": "kokkiri",
    "note": "",
    "examples": {
      "vi": "Con voi rất to.",
      "jp": "象はとても大きいです。",
      "en": "The elephant is very big.",
      "cn": "大象很大。",
      "ko": "코끼리는 아주 큽니다."
    }
  },
  {
    "id": "55",
    "category": "Động vật",
    "vi": "gấu",
    "jp": "熊",
    "kana": "くま",
    "en": "bear",
    "ipa": "/ber/",
    "cn": "熊",
    "pinyin": "xióng",
    "ko": "곰",
    "koreanReading": "gom",
    "note": "",
    "examples": {
      "vi": "Con gấu rất dễ thương.",
      "jp": "熊はかわいいです。",
      "en": "The bear is cute.",
      "cn": "熊很可爱。",
      "ko": "곰은 귀엽습니다."
    }
  },
  {
    "id": "56",
    "category": "Màu sắc",
    "vi": "màu đỏ",
    "jp": "赤",
    "kana": "あか",
    "en": "red",
    "ipa": "/red/",
    "cn": "红色",
    "pinyin": "hóngsè",
    "ko": "빨간색",
    "koreanReading": "ppalgansaek",
    "note": "",
    "examples": {
      "vi": "Tôi thích màu đỏ.",
      "jp": "赤が好きです。",
      "en": "I like red.",
      "cn": "我喜欢红色。",
      "ko": "저는 빨간색을 좋아합니다."
    }
  },
  {
    "id": "57",
    "category": "Màu sắc",
    "vi": "màu xanh dương",
    "jp": "青",
    "kana": "あお",
    "en": "blue",
    "ipa": "/bluː/",
    "cn": "蓝色",
    "pinyin": "lánsè",
    "ko": "파란색",
    "koreanReading": "paransaek",
    "note": "",
    "examples": {
      "vi": "Bầu trời màu xanh dương.",
      "jp": "空は青いです。",
      "en": "The sky is blue.",
      "cn": "天空是蓝色的。",
      "ko": "하늘은 파란색입니다."
    }
  },
  {
    "id": "58",
    "category": "Màu sắc",
    "vi": "màu vàng",
    "jp": "黄色",
    "kana": "きいろ",
    "en": "yellow",
    "ipa": "/ˈjeloʊ/",
    "cn": "黄色",
    "pinyin": "huángsè",
    "ko": "노란색",
    "koreanReading": "noransaek",
    "note": "",
    "examples": {
      "vi": "Bông hoa màu vàng.",
      "jp": "花は黄色です。",
      "en": "The flower is yellow.",
      "cn": "花是黄色的。",
      "ko": "꽃은 노란색입니다."
    }
  },
  {
    "id": "59",
    "category": "Màu sắc",
    "vi": "màu xanh lá",
    "jp": "緑",
    "kana": "みどり",
    "en": "green",
    "ipa": "/ɡriːn/",
    "cn": "绿色",
    "pinyin": "lǜsè",
    "ko": "초록색",
    "koreanReading": "choroksaek",
    "note": "",
    "examples": {
      "vi": "Cây có màu xanh lá.",
      "jp": "木は緑です。",
      "en": "The tree is green.",
      "cn": "树是绿色的。",
      "ko": "나무는 초록색입니다."
    }
  },
  {
    "id": "60",
    "category": "Màu sắc",
    "vi": "màu trắng",
    "jp": "白",
    "kana": "しろ",
    "en": "white",
    "ipa": "/waɪt/",
    "cn": "白色",
    "pinyin": "báisè",
    "ko": "흰색",
    "koreanReading": "huinsaek",
    "note": "",
    "examples": {
      "vi": "Con mèo màu trắng.",
      "jp": "猫は白いです。",
      "en": "The cat is white.",
      "cn": "猫是白色的。",
      "ko": "고양이는 흰색입니다."
    }
  },
  {
    "id": "61",
    "category": "Màu sắc",
    "vi": "màu đen",
    "jp": "黒",
    "kana": "くろ",
    "en": "black",
    "ipa": "/blæk/",
    "cn": "黑色",
    "pinyin": "hēisè",
    "ko": "검은색",
    "koreanReading": "geomeunsaek",
    "note": "",
    "examples": {
      "vi": "Tôi có một chiếc túi màu đen.",
      "jp": "黒い袋があります。",
      "en": "I have a black bag.",
      "cn": "我有一个黑色的袋子。",
      "ko": "검은 가방이 있습니다."
    }
  },
  {
    "id": "62",
    "category": "Màu sắc",
    "vi": "màu hồng",
    "jp": "ピンク",
    "kana": "ぴんく",
    "en": "pink",
    "ipa": "/pɪŋk/",
    "cn": "粉色",
    "pinyin": "fěnsè",
    "ko": "분홍색",
    "koreanReading": "bunhongsaek",
    "note": "",
    "examples": {
      "vi": "Bông hoa màu hồng rất đẹp.",
      "jp": "ピンクの花はきれいです。",
      "en": "The pink flower is beautiful.",
      "cn": "粉色的花很漂亮。",
      "ko": "분홍 꽃이 아름답습니다."
    }
  },
  {
    "id": "63",
    "category": "Màu sắc",
    "vi": "màu tím",
    "jp": "紫",
    "kana": "むらさき",
    "en": "purple",
    "ipa": "/ˈpɜːrpl/",
    "cn": "紫色",
    "pinyin": "zǐsè",
    "ko": "보라색",
    "koreanReading": "borasaek",
    "note": "",
    "examples": {
      "vi": "Tôi thích màu tím.",
      "jp": "紫が好きです。",
      "en": "I like purple.",
      "cn": "我喜欢紫色。",
      "ko": "보라색을 좋아합니다."
    }
  },
  {
    "id": "64",
    "category": "Màu sắc",
    "vi": "màu cam",
    "jp": "オレンジ",
    "kana": "おれんじ",
    "en": "orange",
    "ipa": "/ˈɔːrɪndʒ/",
    "cn": "橙色",
    "pinyin": "chéngsè",
    "ko": "주황색",
    "koreanReading": "juhwangsaek",
    "note": "",
    "examples": {
      "vi": "Quả cam có màu cam.",
      "jp": "オレンジはオレンジ色です。",
      "en": "The orange is orange.",
      "cn": "橙子是橙色的。",
      "ko": "오렌지는 주황색입니다."
    }
  },
  {
    "id": "65",
    "category": "Màu sắc",
    "vi": "màu nâu",
    "jp": "茶色",
    "kana": "ちゃいろ",
    "en": "brown",
    "ipa": "/braʊn/",
    "cn": "棕色",
    "pinyin": "zōngsè",
    "ko": "갈색",
    "koreanReading": "galsaek",
    "note": "",
    "examples": {
      "vi": "Con gấu màu nâu.",
      "jp": "熊は茶色です。",
      "en": "The bear is brown.",
      "cn": "熊是棕色的。",
      "ko": "곰은 갈색입니다."
    }
  },
  {
    "id": "66",
    "category": "Thể thao",
    "vi": "thể thao",
    "jp": "スポーツ",
    "kana": "すぽーつ",
    "en": "sports",
    "ipa": "/spɔːrts/",
    "cn": "运动",
    "pinyin": "yùndòng",
    "ko": "운동",
    "koreanReading": "undong",
    "note": "",
    "examples": {
      "vi": "Tôi thích thể thao.",
      "jp": "スポーツが好きです。",
      "en": "I like sports.",
      "cn": "我喜欢运动。",
      "ko": "저는 운동을 좋아합니다."
    }
  },
  {
    "id": "67",
    "category": "Thể thao",
    "vi": "bóng đá",
    "jp": "サッカー",
    "kana": "さっかー",
    "en": "soccer",
    "ipa": "/ˈsɑːkər/",
    "cn": "足球",
    "pinyin": "zúqiú",
    "ko": "축구",
    "koreanReading": "chukgu",
    "note": "",
    "examples": {
      "vi": "Tôi chơi bóng đá.",
      "jp": "サッカーをします。",
      "en": "I play soccer.",
      "cn": "我踢足球。",
      "ko": "축구를 합니다."
    }
  },
  {
    "id": "68",
    "category": "Thể thao",
    "vi": "bóng rổ",
    "jp": "バスケットボール",
    "kana": "ばすけっとぼーる",
    "en": "basketball",
    "ipa": "/ˈbæskɪtbɔːl/",
    "cn": "篮球",
    "pinyin": "lánqiú",
    "ko": "농구",
    "koreanReading": "nonggu",
    "note": "",
    "examples": {
      "vi": "Anh ấy chơi bóng rổ.",
      "jp": "彼はバスケットボールをします。",
      "en": "He plays basketball.",
      "cn": "他打篮球。",
      "ko": "그는 농구를 합니다."
    }
  },
  {
    "id": "69",
    "category": "Thể thao",
    "vi": "bóng chuyền",
    "jp": "バレーボール",
    "kana": "ばれーぼーる",
    "en": "volleyball",
    "ipa": "/ˈvɑːlibɔːl/",
    "cn": "排球",
    "pinyin": "páiqiú",
    "ko": "배구",
    "koreanReading": "baegu",
    "note": "",
    "examples": {
      "vi": "Chúng tôi chơi bóng chuyền.",
      "jp": "私たちはバレーボールをします。",
      "en": "We play volleyball.",
      "cn": "我们打排球。",
      "ko": "우리는 배구를 합니다."
    }
  },
  {
    "id": "70",
    "category": "Thể thao",
    "vi": "chạy",
    "jp": "走る",
    "kana": "はしる",
    "en": "run",
    "ipa": "/rʌn/",
    "cn": "跑步",
    "pinyin": "pǎobù",
    "ko": "달리다",
    "koreanReading": "dallida",
    "note": "",
    "examples": {
      "vi": "Tôi chạy mỗi sáng.",
      "jp": "毎朝走ります。",
      "en": "I run every morning.",
      "cn": "我每天早上跑步。",
      "ko": "매일 아침 달립니다."
    }
  },
  {
    "id": "71",
    "category": "Thể thao",
    "vi": "bơi",
    "jp": "泳ぐ",
    "kana": "およぐ",
    "en": "swim",
    "ipa": "/swɪm/",
    "cn": "游泳",
    "pinyin": "yóuyǒng",
    "ko": "수영하다",
    "koreanReading": "suyeonghada",
    "note": "",
    "examples": {
      "vi": "Tôi thích bơi.",
      "jp": "泳ぐのが好きです。",
      "en": "I like swimming.",
      "cn": "我喜欢游泳。",
      "ko": "수영을 좋아합니다."
    }
  },
  {
    "id": "72",
    "category": "Thể thao",
    "vi": "xe đạp",
    "jp": "自転車",
    "kana": "じてんしゃ",
    "en": "bicycle",
    "ipa": "/ˈbaɪsɪkl/",
    "cn": "自行车",
    "pinyin": "zìxíngchē",
    "ko": "자전거",
    "koreanReading": "jajeongeo",
    "note": "",
    "examples": {
      "vi": "Tôi đi xe đạp.",
      "jp": "自転車に乗ります。",
      "en": "I ride a bicycle.",
      "cn": "我骑自行车。",
      "ko": "자전거를 탑니다."
    }
  },
  {
    "id": "73",
    "category": "Thể thao",
    "vi": "quần vợt",
    "jp": "テニス",
    "kana": "てにす",
    "en": "tennis",
    "ipa": "/ˈtenɪs/",
    "cn": "网球",
    "pinyin": "wǎngqiú",
    "ko": "테니스",
    "koreanReading": "teniseu",
    "note": "",
    "examples": {
      "vi": "Tôi chơi quần vợt.",
      "jp": "テニスをします。",
      "en": "I play tennis.",
      "cn": "我打网球。",
      "ko": "테니스를 합니다."
    }
  },
  {
    "id": "74",
    "category": "Thể thao",
    "vi": "cầu lông",
    "jp": "バドミントン",
    "kana": "ばどみんとん",
    "en": "badminton",
    "ipa": "/ˈbædmɪntən/",
    "cn": "羽毛球",
    "pinyin": "yǔmáoqiú",
    "ko": "배드민턴",
    "koreanReading": "baedeuminteon",
    "note": "",
    "examples": {
      "vi": "Tôi chơi cầu lông.",
      "jp": "バドミントンをします。",
      "en": "I play badminton.",
      "cn": "我打羽毛球。",
      "ko": "배드민턴을 합니다."
    }
  },
  {
    "id": "75",
    "category": "Thể thao",
    "vi": "đi bộ",
    "jp": "歩く",
    "kana": "あるく",
    "en": "walk",
    "ipa": "/wɔːk/",
    "cn": "散步",
    "pinyin": "sànbù",
    "ko": "걷다",
    "koreanReading": "geotda",
    "note": "",
    "examples": {
      "vi": "Chúng tôi đi bộ trong công viên.",
      "jp": "公園を歩きます。",
      "en": "We walk in the park.",
      "cn": "我们在公园散步。",
      "ko": "공원에서 산책합니다."
    }
  },
  {
    "id": "76",
    "category": "Tình yêu",
    "vi": "tình yêu",
    "jp": "愛",
    "kana": "あい",
    "en": "love",
    "ipa": "/lʌv/",
    "cn": "爱",
    "pinyin": "ài",
    "ko": "사랑",
    "koreanReading": "sarang",
    "note": "",
    "examples": {
      "vi": "Tình yêu làm cuộc sống đẹp hơn.",
      "jp": "愛は人生を豊かにします。",
      "en": "Love makes life beautiful.",
      "cn": "爱让生活更美好。",
      "ko": "사랑은 삶을 아름답게 합니다."
    }
  },
  {
    "id": "77",
    "category": "Tình yêu",
    "vi": "trái tim",
    "jp": "心",
    "kana": "こころ",
    "en": "heart",
    "ipa": "/hɑːrt/",
    "cn": "心",
    "pinyin": "xīn",
    "ko": "마음",
    "koreanReading": "maeum",
    "note": "",
    "examples": {
      "vi": "Tôi có một trái tim ấm áp.",
      "jp": "温かい心があります。",
      "en": "I have a warm heart.",
      "cn": "我有一颗温暖的心。",
      "ko": "따뜻한 마음이 있습니다."
    }
  },
  {
    "id": "78",
    "category": "Tình yêu",
    "vi": "hạnh phúc",
    "jp": "幸せ",
    "kana": "しあわせ",
    "en": "happiness",
    "ipa": "/ˈhæpinəs/",
    "cn": "幸福",
    "pinyin": "xìngfú",
    "ko": "행복",
    "koreanReading": "haengbok",
    "note": "",
    "examples": {
      "vi": "Chúng tôi rất hạnh phúc.",
      "jp": "私たちは幸せです。",
      "en": "We are very happy.",
      "cn": "我们很幸福。",
      "ko": "우리는 행복합니다."
    }
  },
  {
    "id": "79",
    "category": "Tình yêu",
    "vi": "nụ cười",
    "jp": "笑顔",
    "kana": "えがお",
    "en": "smile",
    "ipa": "/smaɪl/",
    "cn": "笑容",
    "pinyin": "xiàoróng",
    "ko": "미소",
    "koreanReading": "miso",
    "note": "",
    "examples": {
      "vi": "Nụ cười của bạn rất đẹp.",
      "jp": "あなたの笑顔はすてきです。",
      "en": "Your smile is beautiful.",
      "cn": "你的笑容很美。",
      "ko": "당신의 미소는 아름답습니다."
    }
  },
  {
    "id": "80",
    "category": "Tình yêu",
    "vi": "bạn",
    "jp": "友達",
    "kana": "ともだち",
    "en": "friend",
    "ipa": "/frend/",
    "cn": "朋友",
    "pinyin": "péngyou",
    "ko": "친구",
    "koreanReading": "chingu",
    "note": "",
    "examples": {
      "vi": "Bạn bè rất quan trọng.",
      "jp": "友達は大切です。",
      "en": "Friends are important.",
      "cn": "朋友很重要。",
      "ko": "친구는 소중합니다."
    }
  },
  {
    "id": "81",
    "category": "Tình yêu",
    "vi": "quà tặng",
    "jp": "贈り物",
    "kana": "おくりもの",
    "en": "gift",
    "ipa": "/ɡɪft/",
    "cn": "礼物",
    "pinyin": "lǐwù",
    "ko": "선물",
    "koreanReading": "seonmul",
    "note": "",
    "examples": {
      "vi": "Tôi chuẩn bị một món quà.",
      "jp": "贈り物を用意します。",
      "en": "I prepare a gift.",
      "cn": "我准备了一份礼物。",
      "ko": "선물을 준비합니다."
    }
  },
  {
    "id": "82",
    "category": "Tình yêu",
    "vi": "hoa",
    "jp": "花",
    "kana": "はな",
    "en": "flower",
    "ipa": "/ˈflaʊər/",
    "cn": "花",
    "pinyin": "huā",
    "ko": "꽃",
    "koreanReading": "kkot",
    "note": "",
    "examples": {
      "vi": "Bông hoa rất đẹp.",
      "jp": "花はきれいです。",
      "en": "The flower is beautiful.",
      "cn": "花很漂亮。",
      "ko": "꽃이 아름답습니다."
    }
  },
  {
    "id": "83",
    "category": "Tình yêu",
    "vi": "lời hứa",
    "jp": "約束",
    "kana": "やくそく",
    "en": "promise",
    "ipa": "/ˈprɑːmɪs/",
    "cn": "约定",
    "pinyin": "yuēdìng",
    "ko": "약속",
    "koreanReading": "yaksok",
    "note": "",
    "examples": {
      "vi": "Chúng ta giữ lời hứa.",
      "jp": "約束を守ります。",
      "en": "We keep our promise.",
      "cn": "我们遵守约定。",
      "ko": "우리는 약속을 지킵니다."
    }
  },
  {
    "id": "84",
    "category": "Tình yêu",
    "vi": "cùng nhau",
    "jp": "一緒",
    "kana": "いっしょ",
    "en": "together",
    "ipa": "/təˈɡeðər/",
    "cn": "一起",
    "pinyin": "yìqǐ",
    "ko": "함께",
    "koreanReading": "hamkke",
    "note": "",
    "examples": {
      "vi": "Chúng ta cùng nhau đi bộ.",
      "jp": "一緒に歩きます。",
      "en": "We walk together.",
      "cn": "我们一起散步。",
      "ko": "함께 걸어갑니다."
    }
  },
  {
    "id": "85",
    "category": "Tình yêu",
    "vi": "ước mơ",
    "jp": "夢",
    "kana": "ゆめ",
    "en": "dream",
    "ipa": "/driːm/",
    "cn": "梦想",
    "pinyin": "mèngxiǎng",
    "ko": "꿈",
    "koreanReading": "kkum",
    "note": "",
    "examples": {
      "vi": "Chúng tôi có một ước mơ đẹp.",
      "jp": "すてきな夢があります。",
      "en": "We have a beautiful dream.",
      "cn": "我们有一个美好的梦想。",
      "ko": "우리는 아름다운 꿈이 있습니다."
    }
  }
];